services:
  frontend:
    build: .
    container_name: frontend-service
    ports:
      - "8081:8081"
    networks:
      - myapp-net
    restart: unless-stopped

networks:
  myapp-net:
    external: true
