version: "3.9"

services:
  backend:
    build: .
    container_name: backend-service

    ports:
      - "8080:8080"
    networks:
      - myapp-net
    depends_on: []
    restart: unless-stopped

networks:
  myapp-net:
    external: true

